version: '3.8'

services:
  app_node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_application
    ports:
      - '3000:3000'
    networks:
      - app_network
    environment:
      NODE_ENV: development

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_balancer
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - app_node
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  app_data:
